////
////  File.swift
////  
////
////  Created by Sam Gauck on 5/2/22.
////
//
//import Foundation
//import BencodingKit
//
//class TrackerConnection {
//    func f() {
//        let tf = (announce: "5", infoHash: 5)
////        let req = URLRequest(url: tf.announce)
//        URLComponents.init(url: <#T##URL#>, resolvingAgainstBaseURL: <#T##Bool#>)
//        let url = URL(string: tf.announce)
//        var u = URLComponents(string: tf.announce)!
//        let s = "hello"
//        let s2 = s[0..<20]
//        print(s2)
//        s.index(s.startIndex, offsetBy: 20)
//        u.queryItems = [
//            URLQueryItem(name: "info_hash", value: tf.infoHash.hexStringEncoded()),
//            URLQueryItem(name: "peer_id", value: "5"),
//            URLQueryItem(name: "port", value: "6881"),
//            URLQueryItem(name: "uploaded", value: "0"),
//            URLQueryItem(name: "downloaded", value: "0"),
//            URLQueryItem(name: "left", value: "\(tf.sfm.length)"),
//            URLQueryItem(name: "event", value: "started")
//        ]
//        u.percentEncodedQuery = u.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")
//        var u2 = URLComponents(string: tf.announce)!
//        u2.queryItems = [
//            URLQueryItem(name: "info_hash", value: tf.infoHash.hexStringEncoded()),
//            URLQueryItem(name: "peer_id", value: "5"),
//            URLQueryItem(name: "port", value: "6881"),
//            URLQueryItem(name: "uploaded", value: "0"),
//            URLQueryItem(name: "downloaded", value: "0"),
//            URLQueryItem(name: "left", value: "\(tf.sfm.length)"),
//            URLQueryItem(name: "event", value: "stopped")
//        ]
//        u2.percentEncodedQuery = u.percentEncodedQuery?.replacingOccurrences(of: "+", with: "%2B")
//        var req = URLRequest(url: u.url!)
//        req.httpMethod = "GET"
//        var req2 = URLRequest(url: u2.url!)
//        req2.httpMethod = "GET"
//        let task = URLSession.shared.dataTask(with: req) { data, response, error in
//            print("r")
//            dump(data)
//            dump(response)
//            dump(error)
//            URLSession.shared.dataTask(with: req2) { data2, response2, error2 in
//                print("r2")
//                dump(data2)
//                dump(response2)
//                dump(error2)
//            }
//        }
//        /*
//         info_hash: urlencoded 20-byte SHA1 hash of the value of the info key from the Metainfo file. Note that the value will be a bencoded dictionary, given the definition of the info key above.
//         peer_id: urlencoded 20-byte string used as a unique ID for the client, generated by the client at startup. This is allowed to be any value, and may be binary data. There are currently no guidelines for generating this peer ID. However, one may rightly presume that it must at least be unique for your local machine, thus should probably incorporate things like process ID and perhaps a timestamp recorded at startup. See peer_id below for common client encodings of this field.
//         port: The port number that the client is listening on. Ports reserved for BitTorrent are typically 6881-6889. Clients may choose to give up if it cannot establish a port within this range.
//         uploaded: The total amount uploaded (since the client sent the 'started' event to the tracker) in base ten ASCII. While not explicitly stated in the official specification, the concensus is that this should be the total number of bytes uploaded.
//         downloaded: The total amount downloaded (since the client sent the 'started' event to the tracker) in base ten ASCII. While not explicitly stated in the official specification, the consensus is that this should be the total number of bytes downloaded.
//         left: The number of bytes this client still has to download in base ten ASCII. Clarification: The number of bytes needed to download to be 100% complete and get all the included files in the torrent.
//         compact: Setting this to 1 indicates that the client accepts a compact response. The peers list is replaced by a peers string with 6 bytes per peer. The first four bytes are the host (in network byte order), the last two bytes are the port (again in network byte order). It should be noted that some trackers only support compact responses (for saving bandwidth) and either refuse requests without "compact=1" or simply send a compact response unless the request contains "compact=0" (in which case they will refuse the request.)
//         no_peer_id: Indicates that the tracker can omit peer id field in peers dictionary. This option is ignored if compact is enabled.
//         event: If specified, must be one of started, completed, stopped, (or empty which is the same as not being specified). If not specified, then this request is one performed at regular intervals.
//         started: The first request to the tracker must include the event key with this value.
//         stopped: Must be sent to the tracker if the client is shutting down gracefully.
//         completed: Must be sent to the tracker when the download completes. However, must not be sent if the download was already 100% complete when the client started. Presumably, this is to allow the tracker to increment the "completed downloads" metric based solely on this event.
//         ip: Optional. The true IP address of the client machine, in dotted quad format or rfc3513 defined hexed IPv6 address. Notes: In general this parameter is not necessary as the address of the client can be determined from the IP address from which the HTTP request came. The parameter is only needed in the case where the IP address that the request came in on is not the IP address of the client. This happens if the client is communicating to the tracker through a proxy (or a transparent web proxy/cache.) It also is necessary when both the client and the tracker are on the same local side of a NAT gateway. The reason for this is that otherwise the tracker would give out the internal (RFC1918) address of the client, which is not routable. Therefore the client must explicitly state its (external, routable) IP address to be given out to external peers. Various trackers treat this parameter differently. Some only honor it only if the IP address that the request came in on is in RFC1918 space. Others honor it unconditionally, while others ignore it completely. In case of IPv6 address (e.g.: 2001:db8:1:2::100) it indicates only that client can communicate via IPv6.
//         numwant: Optional. Number of peers that the client would like to receive from the tracker. This value is permitted to be zero. If omitted, typically defaults to 50 peers.
//         key: Optional. An additional identification that is not shared with any other peers. It is intended to allow a client to prove their identity should their IP address change.
//         trackerid: Optional. If a previous announce contained a tracker id, it should be set here.
//         */
////        URLSession.shared.dataTask(with: .init(string: tf.ann)!)
//    }
//}
